version: "3"

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    volumes:
      - ./back-end:/app
      - ./.env:/app/.env  # Mount .env file into the container at /src/.env
    networks:
      - backend-network
    command: bash -c "npm run prisma:generate && npx prisma migrate dev && npm run seed && npm start"

  frontend:
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
    networks:
      - backend-network

  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
     
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
